### ISSUE TITLE
March 8th TODO List

### ISSUE THREAD

**Issue by sampoder** [PEARL-Project-UC-Berkeley/web-v2#1]
- [x] CRUD for Camera Streams
- [x] Update for Controls
- [x] CRUD for Components
- [x] Basic UI for Camera Streams
    - [x] Ruler Support
- [x] Basic UI for Controls
- [x] Basic UI for Components
- [x] Admin / Non-Admin

**Comment by sampoder** [comment]
We've done it!
